CUDA_VISIBLE_DEVICES=5 OMP_NUM_THREADS=8 nohup python train.py \
	-proj_share_weight \
	-second_sample one \
	-n_layers 5 \
	-feature_attention \
	-scale_emb \
	-flat_method casual_attention \
	-one_step_loss \
	-encoder_pretrained bert-base \
	-fix_encoder \
	-output_dir your_dir \
	-b 128 \
	-trg_len 256 \
	-warmup 4000 \
	-epoch 100 \
	-eval_interval 1 \
	-cvae \
	-use_tb > logs/setting14.log 2>&1 &
